# Install Kubernetes extension, and type `Service` to get the template of this yaml file
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: <Port>
      targetPort: <Target Port>
